import React, { useState } from 'react';
import { DragDropContext, Draggable, Droppable } from '@hello-pangea/dnd';
import { Plus } from 'lucide-react';
import { CUSTOMER_STATUS, useErp } from '@/lib/erpContext';
import { Badge, Button, DataTable, DetailGrid, ErrorBanner, Field, Input, Modal, PageHeader, ReviewDialog, Select, SyncButton, Textarea, TypedSearch, date, idText, statusTone, useTypedFilter } from '@/components/erp/ErpKit';

function CustomerForm({ initial, onSave, onClose }) {
  const [form, setForm] = useState({ Name: initial?.name || '', Email: initial?.email || '', Phone: initial?.phone || '', Company: initial?.company || '', Address: initial?.address || '' });
  const [review, setReview] = useState(false); const [busy, setBusy] = useState(false); const [err, setErr] = useState('');
  const submit = async () => { setBusy(true); setErr(''); const res = await onSave(form, initial); setBusy(false); if (res.success) onClose(); else setErr(res.error); };
  return <><ErrorBanner message={err} /><div className="grid gap-4 md:grid-cols-2"><Field label="Name *"><Input value={form.Name} onChange={(e) => setForm({ ...form, Name: e.target.value })} /></Field><Field label="Phone *"><Input value={form.Phone} onChange={(e) => setForm({ ...form, Phone: e.target.value })} /></Field><Field label="Email"><Input value={form.Email} onChange={(e) => setForm({ ...form, Email: e.target.value })} /></Field><Field label="Company"><Input value={form.Company} onChange={(e) => setForm({ ...form, Company: e.target.value })} /></Field><div className="md:col-span-2"><Field label="Address"><Textarea value={form.Address} onChange={(e) => setForm({ ...form, Address: e.target.value })} /></Field></div></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={() => setReview(true)}>Review Save</Button></div><ReviewDialog open={review} loading={busy} onClose={() => setReview(false)} onConfirm={submit} items={[{ label: 'Name', value: form.Name }, { label: 'Phone', value: form.Phone }, { label: 'Company', value: form.Company }]} /></>;
}
function InteractionForm({ customer, onSave }) { const [type, setType] = useState(5); const [notes, setNotes] = useState(''); const [err, setErr] = useState(''); const save = async () => { const res = await onSave({ CustomerId: customer.customerId, InteractionType: Number(type), Notes: notes, InteractionDate: new Date().toISOString() }); if (res.success) setNotes(''); else setErr(res.error); }; return <div className="mt-6 rounded-3xl bg-slate-50 p-4 dark:bg-slate-900/70"><h3 className="mb-3 font-black">Add Interaction</h3><ErrorBanner message={err} /><div className="grid gap-3 md:grid-cols-4"><Select value={type} onChange={(e) => setType(e.target.value)}><option value="1">Call</option><option value="2">Email</option><option value="3">Meeting</option><option value="4">WhatsApp</option><option value="5">Note</option></Select><div className="md:col-span-2"><Input value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Interaction notes" /></div><Button onClick={save}>Send</Button></div></div>; }

export default function CRM() {
  const { data, loading, errors, syncAllSystemData, saveCustomer, deleteCustomer, changeCustomerStatus, saveInteraction } = useErp();
  const [q, setQ] = useState(''); const [type, setType] = useState('all'); const filtered = useTypedFilter(data.customers, q, type);
  const [modal, setModal] = useState(null); const [selected, setSelected] = useState(null); const [err, setErr] = useState('');
  const onDragEnd = async (result) => { if (!result.destination) return; const customer = data.customers.find((c) => String(c.customerId) === result.draggableId); const status = CUSTOMER_STATUS.find((s) => s.key === result.destination.droppableId); if (!customer || !status || customer.status === status.key) return; const res = await changeCustomerStatus(customer, status.id); if (!res.success) setErr(res.error); };
  const customerInteractions = (customer) => data.interactions.filter((i) => Number(i.customerId) === Number(customer?.customerId));
  return <div><PageHeader title="CRM" subtitle="Customer pipeline, interactions and status tracking" actions={<><SyncButton loading={loading.global} onClick={syncAllSystemData} /><Button onClick={() => setModal({ mode: 'new' })}><Plus className="h-4 w-4" />Customer</Button></>} />
    <ErrorBanner message={err} /><TypedSearch fields={[{ value: 'all', label: 'All Fields' }, { value: 'name', label: 'Name' }, { value: 'company', label: 'Company' }, { value: 'email', label: 'Email' }, { value: 'phone', label: 'Phone' }]} value={q} onValue={setQ} type={type} onType={setType} />
    <DragDropContext onDragEnd={onDragEnd}><div className="mt-6 grid gap-4 xl:grid-cols-5">{CUSTOMER_STATUS.map((status) => { const rows = filtered.filter((c) => c.status === status.key); return <Droppable droppableId={status.key} key={status.key}>{(provided) => <div ref={provided.innerRef} {...provided.droppableProps} className="min-h-[300px] rounded-3xl border border-slate-200 bg-white/95 p-4 dark:border-slate-800 dark:bg-slate-900/95"><div className="mb-4 flex items-center justify-between"><Badge tone={statusTone(status.key)}>{status.name}</Badge><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-black dark:bg-slate-800 dark:text-slate-100">{rows.length}</span></div>{rows.map((c, idx) => <Draggable draggableId={String(c.customerId)} index={idx} key={c.customerId}>{(drag) => <div ref={drag.innerRef} {...drag.draggableProps} {...drag.dragHandleProps} onClick={() => { setSelected(c); setModal({ mode: 'details' }); }} className="mb-3 cursor-pointer rounded-2xl border border-slate-200 bg-slate-50 p-4 shadow-sm transition hover:border-sky-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-800/80 dark:hover:border-sky-500/40"><b>{c.name}</b><p className="text-sm text-slate-500 dark:text-slate-300">{c.company || c.email || c.phone}</p><p className="mt-2 text-xs text-slate-400 dark:text-slate-500">{idText(c.customerId)} · {date(c.createdAt)}</p></div>}</Draggable>)}{provided.placeholder}</div>}</Droppable>; })}</div></DragDropContext>
    <div className="mt-8"><h2 className="mb-3 text-xl font-black">Customers List</h2><DataTable rows={filtered} loading={loading.customers} error={errors.customers} columns={[{ key: 'customerId', label: 'ID', render: (r) => idText(r.customerId) }, { key: 'name', label: 'Name' }, { key: 'company', label: 'Company' }, { key: 'email', label: 'Email' }, { key: 'phone', label: 'Phone' }, { key: 'status', label: 'Status', render: (r) => <Badge tone={statusTone(r.status)}>{r.status}</Badge> }, { key: 'actions', label: 'Actions', render: (r) => <div className="flex gap-2"><Button variant="secondary" onClick={() => { setSelected(r); setModal({ mode: 'details' }); }}>Details</Button><Button variant="secondary" onClick={() => setModal({ mode: 'edit', row: r })}>Edit</Button><Button variant="danger" onClick={() => window.confirm('Delete this record?') && deleteCustomer(r)}>Delete</Button></div> }]} /></div>
    <Modal open={modal?.mode === 'new' || modal?.mode === 'edit'} title={modal?.mode === 'edit' ? 'Edit Customer' : 'New Customer'} subtitle="Enter customer details" onClose={() => setModal(null)}><CustomerForm initial={modal?.row} onSave={saveCustomer} onClose={() => setModal(null)} /></Modal>
    <Modal open={modal?.mode === 'details'} title={selected?.name || 'Customer'} subtitle="Customer info, interactions and CRM status" onClose={() => setModal(null)} size="max-w-6xl"><DetailGrid items={[{ label: 'ID', value: idText(selected?.customerId) }, { label: 'Company', value: selected?.company }, { label: 'Email', value: selected?.email }, { label: 'Phone', value: selected?.phone }, { label: 'Address', value: selected?.address }, { label: 'Status', value: selected?.status }, { label: 'Created', value: date(selected?.createdAt) }]} /><InteractionForm customer={selected || {}} onSave={saveInteraction} /><div className="mt-6"><h3 className="mb-3 font-black">Interactions</h3><DataTable rows={customerInteractions(selected)} columns={[{ key: 'interactionId', label: 'ID', render: (r) => idText(r.interactionId) }, { key: 'type', label: 'Type' }, { key: 'notes', label: 'Notes' }, { key: 'date', label: 'Date', render: (r) => date(r.date) }]} /></div></Modal>
  </div>;
}
