import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Plus } from 'lucide-react';
import { useErp } from '@/lib/erpContext';
import { Badge, Button, DataTable, DetailGrid, ErrorBanner, Field, Input, Modal, PageHeader, ReviewDialog, Select, SyncButton, Textarea, TypedSearch, date, idText, money, statusTone, useTypedFilter } from '@/components/erp/ErpKit';

function ProductForm({ initial, suppliers, onSave, onClose }) {
  const [form, setForm] = useState({ ProductCode: initial?.productCode || '', Name: initial?.name || '', Description: initial?.description || '', Category: initial?.category || '', Quantity: initial?.quantity ?? 0, MinimumStockLevel: initial?.minimumStockLevel ?? 5, PurchasePrice: initial?.purchasePrice ?? 0, SellingPrice: initial?.sellingPrice ?? 0, SupplierId: initial?.supplierId || '' });
  const [review, setReview] = useState(false); const [busy, setBusy] = useState(false); const [err, setErr] = useState('');
  const submit = async () => { setBusy(true); setErr(''); const body = { ...form, Quantity: Number(form.Quantity), MinimumStockLevel: Number(form.MinimumStockLevel), PurchasePrice: Number(form.PurchasePrice), SellingPrice: Number(form.SellingPrice), SupplierId: form.SupplierId ? Number(form.SupplierId) : null }; const res = await onSave(body, initial); setBusy(false); if (res.success) onClose(); else setErr(res.error); };
  return <><ErrorBanner message={err} /><div className="grid gap-4 md:grid-cols-2"><Field label="Product Code *"><Input disabled={!!initial} value={form.ProductCode} onChange={(e) => setForm({ ...form, ProductCode: e.target.value })} /></Field><Field label="Product Name *"><Input value={form.Name} onChange={(e) => setForm({ ...form, Name: e.target.value })} /></Field><Field label="Category"><Input value={form.Category} onChange={(e) => setForm({ ...form, Category: e.target.value })} /></Field><Field label="Supplier"><Select value={form.SupplierId || ''} onChange={(e) => setForm({ ...form, SupplierId: e.target.value })}><option value="">No supplier</option>{suppliers.map((s) => <option key={s.supplierId} value={s.supplierId}>{s.name} — ID {s.supplierId}</option>)}</Select></Field><Field label="Quantity"><Input type="number" value={form.Quantity} onChange={(e) => setForm({ ...form, Quantity: e.target.value })} /></Field><Field label="Minimum Stock Level"><Input type="number" value={form.MinimumStockLevel} onChange={(e) => setForm({ ...form, MinimumStockLevel: e.target.value })} /></Field><Field label="Purchase Price"><Input type="number" value={form.PurchasePrice} onChange={(e) => setForm({ ...form, PurchasePrice: e.target.value })} /></Field><Field label="Selling Price"><Input type="number" value={form.SellingPrice} onChange={(e) => setForm({ ...form, SellingPrice: e.target.value })} /></Field><div className="md:col-span-2"><Field label="Description"><Textarea value={form.Description} onChange={(e) => setForm({ ...form, Description: e.target.value })} /></Field></div></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={() => setReview(true)}>Review Save</Button></div><ReviewDialog open={review} loading={busy} onClose={() => setReview(false)} onConfirm={submit} items={[{ label: 'Product', value: form.Name }, { label: 'Code', value: form.ProductCode }, { label: 'Supplier ID', value: form.SupplierId }, { label: 'Selling Price', value: money(form.SellingPrice) }]} /></>;
}

function AdjustStock({ product, onAdjust, onClose }) {
  const [qty, setQty] = useState(0); const [reason, setReason] = useState('Manual inventory adjustment'); const [notes, setNotes] = useState(''); const [review, setReview] = useState(false); const [err, setErr] = useState('');
  const submit = async () => { const res = await onAdjust({ ProductId: product.productId, AdjustmentQuantity: Number(qty), Reason: reason, Notes: notes }); if (res.success) onClose(); else setErr(res.error); };
  return <><ErrorBanner message={err} /><div className="grid gap-4"><Field label="Signed Adjustment Quantity"><Input type="number" value={qty} onChange={(e) => setQty(e.target.value)} /></Field><Field label="Reason min 5 chars"><Input value={reason} onChange={(e) => setReason(e.target.value)} /></Field><Field label="Notes"><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></Field></div><div className="mt-6 flex justify-end"><Button onClick={() => setReview(true)}>Review Adjustment</Button></div><ReviewDialog open={review} onClose={() => setReview(false)} onConfirm={submit} items={[{ label: 'Product', value: product.name }, { label: 'AdjustmentQuantity', value: qty }, { label: 'Reason', value: reason }]} /></>;
}

export default function Inventory() {
  const { data, loading, errors, syncAllSystemData, saveProduct, deleteProduct, adjustStock, getProductDetails } = useErp();
  const [searchParams] = useSearchParams();
  const [tab, setTab] = useState('products'); const [q, setQ] = useState(''); const [type, setType] = useState('all'); const [lowStockOnly, setLowStockOnly] = useState(searchParams.get('filter') === 'low-stock'); const [modal, setModal] = useState(null); const [selected, setSelected] = useState(null);
  useEffect(() => { if (searchParams.get('filter') === 'low-stock') { setTab('products'); setLowStockOnly(true); } }, [searchParams]);
  const filteredProducts = useTypedFilter(data.products, q, type);
  const products = lowStockOnly ? filteredProducts.filter((p) => p.isLowStock) : filteredProducts;
  const productMovements = (p) => data.movements.filter((m) => Number(m.productId) === Number(p?.productId));
  const showDetails = async (row) => { const fresh = await getProductDetails(row); setSelected(fresh); setModal({ mode: 'details' }); };
  return <div><PageHeader title="Products & Inventory" subtitle="Products, stock, low stock and inventory movements" actions={<><SyncButton loading={loading.global} onClick={syncAllSystemData} /><Button variant={lowStockOnly ? 'warning' : 'secondary'} onClick={() => { setTab('products'); setLowStockOnly((v) => !v); }}>Low Stock</Button><Button onClick={() => setModal({ mode: 'new' })}><Plus className="h-4 w-4" /> Product</Button></>} />
    <div className="mb-5 flex gap-2"><Button variant={tab === 'products' ? 'primary' : 'secondary'} onClick={() => setTab('products')}>Products</Button><Button variant={tab === 'movements' ? 'primary' : 'secondary'} onClick={() => setTab('movements')}>Inventory Movements</Button></div>
    {tab === 'products' && <><TypedSearch value={q} onValue={setQ} type={type} onType={setType} fields={[{ value: 'all', label: 'All Fields' }, { value: 'name', label: 'Name' }, { value: 'productCode', label: 'Code' }, { value: 'category', label: 'Category' }, { value: 'supplierName', label: 'Supplier' }]} /><div className="mt-5"><DataTable loading={loading.products} error={null} rows={products} columns={[{ key: 'productId', label: 'ID', render: (r) => idText(r.productId) }, { key: 'productCode', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'category', label: 'Category' }, { key: 'supplierName', label: 'Supplier' }, { key: 'quantity', label: 'Qty' }, { key: 'sellingPrice', label: 'Selling', render: (r) => money(r.sellingPrice) }, { key: 'low', label: 'Low Stock', render: (r) => <Badge tone={r.isLowStock ? 'amber' : 'green'}>{r.isLowStock ? `Yes (${r.stockDeficit})` : 'No'}</Badge> }, { key: 'actions', label: 'Actions', render: (r) => <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => showDetails(r)}>Details</Button><Button variant="secondary" onClick={() => setModal({ mode: 'edit', row: r })}>Edit</Button><Button variant="warning" onClick={() => { setSelected(r); setModal({ mode: 'adjust' }); }}>Adjust</Button><Button variant="danger" onClick={() => window.confirm('Delete this product?') && deleteProduct(r)}>Delete</Button></div> }]} /></div></>}
    {tab === 'movements' && <DataTable loading={loading.movements} error={null} rows={data.movements} columns={[{ key: 'movementId', label: 'ID', render: (r) => idText(r.movementId) }, { key: 'productCode', label: 'Code' }, { key: 'productName', label: 'Product' }, { key: 'movementTypeText', label: 'Type', render: (r) => <Badge tone={statusTone(r.movementTypeText)}>{r.movementTypeText}</Badge> }, { key: 'quantity', label: 'Qty' }, { key: 'referenceNumber', label: 'Reference' }, { key: 'movementDate', label: 'Date', render: (r) => date(r.movementDate) }, { key: 'notes', label: 'Notes' }]} />}
    <Modal open={modal?.mode === 'new' || modal?.mode === 'edit'} title={modal?.mode === 'edit' ? 'Edit Product' : 'New Product'} subtitle="Product details" onClose={() => setModal(null)}><ProductForm initial={modal?.row} suppliers={data.suppliers} onSave={saveProduct} onClose={() => setModal(null)} /></Modal>
    <Modal open={modal?.mode === 'adjust'} title="Adjust Stock" subtitle="Adjust stock quantity" onClose={() => setModal(null)}><AdjustStock product={selected || {}} onAdjust={adjustStock} onClose={() => setModal(null)} /></Modal>
    <Modal open={modal?.mode === 'details'} title={selected?.name || 'Product Details'} subtitle="Supplier, stock, low stock, movements and usage" onClose={() => setModal(null)} size="max-w-6xl"><DetailGrid items={[{ label: 'ID', value: idText(selected?.productId) }, { label: 'Code', value: selected?.productCode }, { label: 'Supplier', value: selected?.supplierName || selected?.supplierId }, { label: 'Category', value: selected?.category }, { label: 'Qty', value: selected?.quantity }, { label: 'Min Stock', value: selected?.minimumStockLevel }, { label: 'Purchase', value: money(selected?.purchasePrice) }, { label: 'Selling', value: money(selected?.sellingPrice) }, { label: 'Profit', value: money(selected?.profitMargin) }, { label: 'Low Stock', value: selected?.isLowStock ? 'Yes' : 'No' }, { label: 'Stock Deficit', value: selected?.stockDeficit }, { label: 'Updated', value: date(selected?.updatedAt) }]} /><div className="mt-6"><h3 className="mb-3 font-black">Product Movements</h3><DataTable rows={productMovements(selected)} columns={[{ key: 'movementId', label: 'ID', render: (r) => idText(r.movementId) }, { key: 'movementTypeText', label: 'Type' }, { key: 'quantity', label: 'Qty' }, { key: 'referenceNumber', label: 'Reference' }, { key: 'movementDate', label: 'Date', render: (r) => date(r.movementDate) }, { key: 'notes', label: 'Notes' }]} /></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sky-950 dark:border-sky-500/30 dark:bg-sky-500/10 dark:text-sky-100"><b>Quotation Usage</b><p className="mt-2 text-3xl font-black">{data.quotations.filter((q) => q.items?.some((it) => Number(it.productId) === Number(selected?.productId))).length}</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-950 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-100"><b>Sales Usage</b><p className="mt-2 text-3xl font-black">{data.sales.filter((s) => s.items?.some((it) => Number(it.productId) === Number(selected?.productId))).length}</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-950 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-100"><b>PO Usage</b><p className="mt-2 text-3xl font-black">{data.purchaseOrders.filter((po) => po.items?.some((it) => Number(it.productId) === Number(selected?.productId))).length}</p></div></div></Modal>
  </div>;
}
