import React, { useState } from 'react';
import { Plus, Printer } from 'lucide-react';
import { useErp } from '@/lib/erpContext';
import { Badge, Button, DataTable, DetailGrid, ErrorBanner, Field, Input, Modal, PageHeader, ReviewDialog, Select, SyncButton, Textarea, TypedSearch, date, idText, money, statusTone, useTypedFilter } from '@/components/erp/ErpKit';

function SupplierForm({ initial, onSave, onClose }) {
  const [form, setForm] = useState({ Name: initial?.name || '', Email: initial?.email || '', Phone: initial?.phone || '', Address: initial?.address || '' });
  const [review, setReview] = useState(false); const [busy, setBusy] = useState(false); const [err, setErr] = useState('');
  const submit = async () => { setBusy(true); setErr(''); const res = await onSave(form, initial); setBusy(false); if (res.success) onClose(); else setErr(res.error); };
  return <><ErrorBanner message={err} /><div className="grid gap-4 md:grid-cols-2"><Field label="Name *"><Input value={form.Name} onChange={(e) => setForm({ ...form, Name: e.target.value })} /></Field><Field label="Email"><Input value={form.Email} onChange={(e) => setForm({ ...form, Email: e.target.value })} /></Field><Field label="Phone"><Input value={form.Phone} onChange={(e) => setForm({ ...form, Phone: e.target.value })} /></Field><Field label="Address"><Input value={form.Address} onChange={(e) => setForm({ ...form, Address: e.target.value })} /></Field></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={() => setReview(true)}>Review Save</Button></div><ReviewDialog open={review} loading={busy} onClose={() => setReview(false)} onConfirm={submit} items={[{ label: 'Supplier', value: form.Name }, { label: 'Email', value: form.Email }, { label: 'Phone', value: form.Phone }]} /></>;
}
function POForm({ products, suppliers, onSave, onClose }) {
  const [supplierId, setSupplierId] = useState(''); const [notes, setNotes] = useState(''); const [items, setItems] = useState([{ ProductId: '', Quantity: 1, UnitPrice: 0 }]); const [review, setReview] = useState(false); const [err, setErr] = useState('');
  const setItem = (i, patch) => setItems((prev) => prev.map((it, idx) => idx === i ? { ...it, ...patch } : it));
  const submit = async () => { const body = { SupplierId: Number(supplierId), Notes: notes, Items: items.filter((x) => x.ProductId).map((x) => ({ ProductId: Number(x.ProductId), Quantity: Number(x.Quantity), UnitPrice: Number(x.UnitPrice) })) }; const res = await onSave(body); if (res.success) onClose(); else setErr(res.error); };
  return <><ErrorBanner message={err} /><Field label="Supplier *"><Select value={supplierId} onChange={(e) => setSupplierId(e.target.value)}><option value="">Select supplier</option>{suppliers.map((s) => <option key={s.supplierId} value={s.supplierId}>{s.name} — ID {s.supplierId}</option>)}</Select></Field><div className="mt-5 rounded-3xl bg-slate-50 p-4"><h3 className="mb-3 font-black">Line Items</h3>{items.map((it, i) => <div key={i} className="mb-3 grid gap-3 md:grid-cols-4"><Select value={it.ProductId} onChange={(e) => { const p = products.find((x) => Number(x.productId) === Number(e.target.value)); setItem(i, { ProductId: e.target.value, UnitPrice: p?.purchasePrice || 0 }); }}><option value="">Product</option>{products.map((p) => <option key={p.productId} value={p.productId}>{p.productCode} — {p.name}</option>)}</Select><Input type="number" value={it.Quantity} onChange={(e) => setItem(i, { Quantity: e.target.value })} /><Input type="number" value={it.UnitPrice} onChange={(e) => setItem(i, { UnitPrice: e.target.value })} /><Button variant="secondary" onClick={() => setItems((prev) => prev.filter((_, idx) => idx !== i))}>Remove</Button></div>)}<Button variant="secondary" onClick={() => setItems([...items, { ProductId: '', Quantity: 1, UnitPrice: 0 }])}>Add Item</Button></div><Field label="Notes"><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><div className="mt-6 flex justify-end"><Button onClick={() => setReview(true)}>Review Purchase Order</Button></div><ReviewDialog open={review} onClose={() => setReview(false)} onConfirm={submit} items={[{ label: 'Supplier ID', value: supplierId }, { label: 'Items', value: items.filter((x) => x.ProductId).length }, { label: 'Notes', value: notes }]} /></>;
}

export default function Purchase() {
  const { data, loading, errors, syncAllSystemData, saveSupplier, deleteSupplier, getSupplierDetails, savePurchaseOrder, sendPurchaseOrder, receivePurchaseOrder, deletePurchaseOrder, getPurchaseOrderDetails, getPurchaseOrderDocument } = useErp();
  const [tab, setTab] = useState('suppliers'); const [q, setQ] = useState(''); const [type, setType] = useState('all'); const [modal, setModal] = useState(null); const [selected, setSelected] = useState(null); const [doc, setDoc] = useState(null); const [err, setErr] = useState('');
  const suppliers = useTypedFilter(data.suppliers, q, type);
  const getPoStatus = (po) => po?.statusName || po?.statusText || '';
  const showSupplier = async (s) => { const fresh = await getSupplierDetails(s); setSelected(fresh); setModal({ mode: 'supplierDetails' }); };
  const showPO = async (po) => { const fresh = await getPurchaseOrderDetails(po); setSelected(fresh); setModal({ mode: 'poDetails' }); };
  const showDoc = async (po) => { setErr(''); try { setDoc(await getPurchaseOrderDocument(po)); setModal({ mode: 'doc' }); } catch (e) { setErr(e.message); } };
  return <div><PageHeader title="Purchase" subtitle="Suppliers, purchase orders and printable documents" actions={<><SyncButton loading={loading.global} onClick={syncAllSystemData} /><Button onClick={() => setModal(tab === 'suppliers' ? { mode: 'newSupplier' } : { mode: 'newPO' })}><Plus className="h-4 w-4" /> New {tab === 'suppliers' ? 'Supplier' : 'PO'}</Button></>} />
    <ErrorBanner message={err} /><div className="mb-5 flex gap-2"><Button variant={tab === 'suppliers' ? 'primary' : 'secondary'} onClick={() => setTab('suppliers')}>Suppliers</Button><Button variant={tab === 'orders' ? 'primary' : 'secondary'} onClick={() => setTab('orders')}>Purchase Orders</Button></div>
    {tab === 'suppliers' && <><TypedSearch value={q} onValue={setQ} type={type} onType={setType} fields={[{ value: 'all', label: 'All Fields' }, { value: 'name', label: 'Name' }, { value: 'email', label: 'Email' }, { value: 'phone', label: 'Phone' }]} /><div className="mt-5"><DataTable loading={loading.suppliers} error={errors.suppliers} rows={suppliers} columns={[{ key: 'supplierId', label: 'ID', render: (r) => idText(r.supplierId) }, { key: 'name', label: 'Supplier' }, { key: 'email', label: 'Email' }, { key: 'phone', label: 'Phone' }, { key: 'productCount', label: 'Products' }, { key: 'purchaseOrderCount', label: 'POs' }, { key: 'actions', label: 'Actions', render: (r) => <div className="flex gap-2"><Button variant="secondary" onClick={() => showSupplier(r)}>Details</Button><Button variant="secondary" onClick={() => setModal({ mode: 'editSupplier', row: r })}>Edit</Button><Button variant="danger" onClick={() => window.confirm('Delete this supplier?') && deleteSupplier(r)}>Delete</Button></div> }]} /></div></>}
    {tab === 'orders' && <DataTable loading={loading.purchaseOrders} error={errors.purchaseOrders} rows={data.purchaseOrders} columns={[{ key: 'purchaseOrderId', label: 'ID', render: (r) => idText(r.purchaseOrderId) }, { key: 'poNumber', label: 'PO Number' }, { key: 'supplierName', label: 'Supplier' }, { key: 'totalItems', label: 'Items' }, { key: 'totalAmount', label: 'Total', render: (r) => money(r.totalAmount) }, { key: 'statusName', label: 'Status', render: (r) => <Badge tone={statusTone(getPoStatus(r))}>{getPoStatus(r)}</Badge> }, { key: 'orderDate', label: 'Order Date', render: (r) => date(r.orderDate) }, { key: 'actions', label: 'Actions', render: (r) => <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => showPO(r)}>Details</Button>{getPoStatus(r) === 'Draft' && <Button onClick={() => sendPurchaseOrder(r)}>Send</Button>}{getPoStatus(r) === 'Sent' && <Button variant="success" onClick={() => receivePurchaseOrder(r, 'Received from UI')}>Receive</Button>}{getPoStatus(r) === 'Draft' && <Button variant="secondary" onClick={() => showDoc(r)}><Printer className="h-4 w-4" />Doc</Button>}<Button variant="danger" onClick={() => window.confirm('Delete this purchase order?') && deletePurchaseOrder(r)}>Delete</Button></div> }]} />}
    <Modal open={modal?.mode === 'newSupplier' || modal?.mode === 'editSupplier'} title={modal?.mode === 'editSupplier' ? 'Edit Supplier' : 'New Supplier'} onClose={() => setModal(null)}><SupplierForm initial={modal?.row} onSave={saveSupplier} onClose={() => setModal(null)} /></Modal>
    <Modal open={modal?.mode === 'newPO'} title="New Purchase Order" subtitle="Create purchase order" onClose={() => setModal(null)} size="max-w-5xl"><POForm products={data.products} suppliers={data.suppliers} onSave={savePurchaseOrder} onClose={() => setModal(null)} /></Modal>
    <Modal open={modal?.mode === 'supplierDetails'} title={selected?.name || 'Supplier Details'} subtitle="Info, products, purchase orders, totals and stock summary" onClose={() => setModal(null)} size="max-w-6xl"><DetailGrid items={[{ label: 'ID', value: idText(selected?.supplierId) }, { label: 'Email', value: selected?.email }, { label: 'Phone', value: selected?.phone }, { label: 'Address', value: selected?.address }, { label: 'Products', value: selected?.totalProductsSupplied ?? selected?.productCount }, { label: 'POs', value: selected?.totalPurchaseOrders ?? selected?.purchaseOrderCount }, { label: 'Amount Spent', value: money(selected?.totalAmountSpent) }, { label: 'Created', value: date(selected?.createdAt) }]} /><h3 className="mt-6 mb-3 font-black">Products Supplied</h3><DataTable rows={selected?.products || data.products.filter((p) => Number(p.supplierId) === Number(selected?.supplierId))} columns={[{ key: 'productCode', label: 'Code' }, { key: 'name', label: 'Product' }, { key: 'quantity', label: 'Qty' }, { key: 'minimumStockLevel', label: 'Min' }, { key: 'isLowStock', label: 'Low', render: (r) => <Badge tone={r.isLowStock ? 'amber' : 'green'}>{r.isLowStock ? 'Yes' : 'No'}</Badge> }]} /><h3 className="mt-6 mb-3 font-black">Purchase Orders</h3><DataTable rows={selected?.purchaseOrders || data.purchaseOrders.filter((po) => Number(po.supplierId) === Number(selected?.supplierId))} columns={[{ key: 'poNumber', label: 'PO' }, { key: 'totalAmount', label: 'Total', render: (r) => money(r.totalAmount) }, { key: 'statusText', label: 'Status', render: (r) => <Badge tone={statusTone(r.statusText || r.statusName)}>{r.statusText || r.statusName}</Badge> }, { key: 'orderDate', label: 'Date', render: (r) => date(r.orderDate) }]} /></Modal>
    <Modal open={modal?.mode === 'poDetails'} title={selected?.poNumber || 'Purchase Order Details'} subtitle="Rich PO details and line items" onClose={() => setModal(null)} size="max-w-6xl"><DetailGrid items={[{ label: 'ID', value: idText(selected?.purchaseOrderId) }, { label: 'Supplier', value: selected?.supplierName }, { label: 'Status', value: selected?.statusName }, { label: 'Total', value: money(selected?.totalAmount) }, { label: 'Items', value: selected?.totalItems }, { label: 'Quantity', value: selected?.totalQuantity }, { label: 'Order Date', value: date(selected?.orderDate) }, { label: 'Received', value: date(selected?.receivedDate) }]} /><h3 className="mt-6 mb-3 font-black">Line Items</h3><DataTable rows={selected?.items || []} columns={[{ key: 'productCode', label: 'Code' }, { key: 'productName', label: 'Product' }, { key: 'quantity', label: 'Qty' }, { key: 'unitPrice', label: 'Unit', render: (r) => money(r.unitPrice) }, { key: 'lineTotal', label: 'Total', render: (r) => money(r.lineTotal) }]} /></Modal>
    <Modal open={modal?.mode === 'doc'} title="Purchase Order Document" subtitle="Purchase order document" onClose={() => setModal(null)} size="max-w-5xl"><div id="po-doc" className="rounded-3xl border bg-white p-8 text-slate-950"><div className="flex flex-wrap items-start justify-between gap-6 border-b pb-6"><div className="flex items-center gap-4"><img src="/small-pro-logo-transparent.png" alt="Small Pro ERP" className="h-14 w-auto" /><div><h2 className="text-4xl font-black">Purchase Order</h2><p className="text-slate-500">{doc?.companyName || 'Small Pro'}</p></div></div><div className="text-right"><p><b>Order:</b> {doc?.poNumber || doc?.pONumber}</p><p><b>Date:</b> {date(doc?.orderDate)}</p><p><b>Expected:</b> {date(doc?.expectedDeliveryDate)}</p></div></div><div className="my-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border p-4"><h3 className="font-black">Supplier</h3><p>{doc?.supplierName}</p><p>{doc?.supplierEmail}</p><p>{doc?.supplierPhone}</p><p>{doc?.supplierAddress}</p></div><div className="rounded-2xl border p-4"><h3 className="font-black">Summary</h3><p>Total Items: {doc?.totalItems}</p><p>Total Quantity: {doc?.totalQuantity}</p><p className="text-2xl font-black">{money(doc?.totalAmount)}</p></div></div><DataTable rows={doc?.items || []} columns={[{ key: 'itemNumber', label: '#' }, { key: 'productCode', label: 'Code' }, { key: 'productName', label: 'Product' }, { key: 'quantity', label: 'Qty' }, { key: 'unitPrice', label: 'Unit', render: (r) => money(r.unitPrice) }, { key: 'lineTotal', label: 'Total', render: (r) => money(r.lineTotal) }]} /><div className="mt-6 grid gap-4 md:grid-cols-2"><div><h3 className="font-black">Notes</h3><p>{doc?.notes || '—'}</p></div><div><h3 className="font-black">Payment Terms</h3><p>{doc?.paymentTerms || '—'}</p></div></div></div><div className="mt-4 flex justify-end"><Button onClick={() => window.print()}><Printer className="h-4 w-4" /> Print</Button></div></Modal>
  </div>;
}
